darwin-eu/CohortCharacteristics

- R/summariseLargeScaleCharacteristics.R
for https://github.com/darwin-eu-dev/CohortCharacteristics/issues/1
> print progress of summariseLSC

- R/summariseLargeScaleCharacteristics.R
- tests/testthat/test-summariseLargeScaleCharacteristics.R
for https://github.com/darwin-eu-dev/CohortCharacteristics/issues/2
> message about dropping records for frequency in lsc

- R/plotCohortTiming.R
- R/summariseCohortTiming.R
- R/tableCohortTiming.R
- man/CohortCharacteristics-package.Rd
- man/plotCohortTiming.Rd
- man/tableCohortTiming.Rd
- vignettes/a09_summariseCohortTiming.Rmd
- add timeScale argument to plotCohortTiming and tableCohortTiming #42 
- specify if days or years in labelling of estimates
- update vignettes
> cohort timing output updates

- R/plotCohortOverlap.R
- R/tableCohortOverlap.R
- man/plotCohortOverlap.Rd
- tests/testthat/test-tableSummarised.R
- vignettes/a08_summariseCohortOverlap.Rmd
- reduce plotCohortOverlap options and tweaks to plot #7
- slightly changed labels for tableCohortOverlap
- vignette on cohort overlap #3
> cohort overlap output

- R/plotCohortOverlap.R
- R/plotCohortTiming.R
- R/plotInternal.R
- man/plotCohortOverlap.Rd
- man/plotCohortTiming.Rd
- tests/testthat/test-plotSummarised.R
- vignettes/a08_summariseCohortOverlap.Rmd
- vignettes/a09_summariseCohortTiming.Rmd
improving alignment with https://darwin-eu.github.io/IncidencePrevalence/reference/plotIncidence.html
> simplify and align plotCohortTiming arguments

- R/plotCharacteristics.R
- man/plotCharacteristics.Rd
- tests/testthat/test-plotCharacteristics.R
- tests/testthat/test-plotSummarised.R
- vignettes/a06_summarisePatientCharacteristics.Rmd
> Characteristics output

- R/tableLargeScaleCharacteristics.R
- man/tableLargeScaleCharacteristics.Rd
- vignettes/a07_summariseLargeScaleCharacteristics.Rmd
- expand vignette
- alphabetical ordering of tableLSC
- tableLSC - default all results
> tableLSC and vignette

- R/tableCharacteristics.R
- vignettes/a06_summarisePatientCharacteristics.Rmd
- ensure order of characteristics table
- additional examples in vignette showing more functionality
> characteristics table and vignette

- R/summariseCohortOverlap.R
- R/summariseLargeScaleCharacteristics.R
- man/summariseCohortOverlap.Rd
> add settings separately

- R/summariseCharacteristics.R
- man/summariseCharacteristics.Rd
> Summarise characteristics example

- R/tableCharacteristics.R
- tests/testthat/test-tableSummarised.R
> throwing informative warnings

- R/plotCohortTiming.R
> correct x and y labels

- R/plotCharacteristics.R
- R/plotCohortAttrition.R
- R/plotCohortOverlap.R
- R/plotCohortTiming.R
- R/plotComparedLargeScaleCharacteristics.R
- R/tableCharacteristics.R
- R/tableCohortAttrition.R
- R/tableCohortOverlap.R
- R/tableCohortTiming.R
- R/tableLargeScaleCharacteristics.R
- tests/testthat/test-plotCohortAttrition.R
- tests/testthat/test-tableSummarised.R
> empty tables and plots

- R/summariseCharacteristics.R
- tests/testthat/test-summariseCharacteristics.R
> add cohort names if the cohort is empty

- DESCRIPTION
- R/summariseCharacteristics.R
- man/summariseCharacteristics.Rd
- tests/testthat/test-summariseCharacteristics.R
- tests/testthat/test-tableSummarised.R
> add days in cohort

- DESCRIPTION
- R/plotCohortTiming.R
- R/summariseCohortTiming.R
- R/tableCohortTiming.R
- man/summariseCohortTiming.Rd
- tests/testthat/test-summariseCohortTiming.R
- vignettes/a09_summariseCohortTiming.Rmd
> density -> estimates

- DESCRIPTION
- R/checks.R
- R/plotInternal.R
- R/plotLargeScaleCharacteristics.R
- R/summariseCharacteristics.R
- R/summariseCohortOverlap.R
- R/summariseCohortTiming.R
- R/summariseLargeScaleCharacteristics.R
- R/tableCharacteristics.R
- R/tableCohortCount.R
- R/tableCohortOverlap.R
- R/tableCohortTiming.R
> remove checkamte

- DESCRIPTION
- README.Rmd
- README.md
> add citation in readme

- R/tableCohortCount.R
- R/tableCohortOverlap.R
- R/tableCohortTiming.R
- man/tableCohortCount.Rd
- man/tableCohortOverlap.Rd
- man/tableCohortTiming.Rd
> eliminate hide argument

- R/plotCharacteristics.R
- R/plotCohortTiming.R
- tests/testthat/test-plotCohortTiming.R
> minimum 5 days in x axis for plots
